### ISSUE TITLE
Add name= to your example

### ISSUE THREAD

**Issue by FellowMD** [Blooie/ember-radio-buttons#1]
First off thanks for actually packaging this into add-on form, I wasn't sure how to do it. Did you see both my solutions? It looks like you went with the simpler of the two, but in this one you do have to pass name='some-group-name' so that the radio buttons will bind into a group.
so it should be `{{radio-button name='numbers' value='one' checked=selectedNumber}}` instead of `{{radio-button value='one' checked=selectedNumber}}` in your readme

**Comment by mansona** [comment]
I'm closing this because it seems to be working as is. If you want I can re-open it
