### ISSUE TITLE
Add action?

### ISSUE THREAD

**Issue by albertpak** [Blooie/ember-radio-buttons#10]
how do i add an action to this radio-button that i want to run when user selects it?

I saw pull request #9 - is it related to this?

**Comment by mszoernyi** [comment]
@albertpak Yes. Use the branch from the PR and set  `changed=actionTobeCalled` on the radio button.

**Comment by albertpak** [comment]
ok, thank you :smile:

**Comment by mansona** [comment]
Closing this issue in favour of the discussion on #9
