### ISSUE TITLE
Broken Tests

### ISSUE THREAD

**Issue by lumir** [Blooie/ember-radio-buttons#2]
I'm using this awesome add-on inside a component template and it's working really well, but it's breaking the tests with this message: 

Could not find property 'radio-button' on object <(subclass of Ember.Component):ember486>.

can you help me with this?

**Comment by slightlytyler** [comment]
@lumir did you ever get this figured out?

**Comment by mansona** [comment]
@slightlytyler if you are having this same problem you could help us create a failing test to fix. Do you have a use case where this is failing a test?

**Comment by slightlytyler** [comment]
Working on a unit test for a component that uses the `radio-button` component. Same error as above, if I add `needs: ['component:radio-button']` I get `TypeError: Attempting to register an unknown factory: component:radio-button`. Guessing I need to initialize `ember-radio-buttons` inside the test but not sure how to do that.

Anyway here's the test.

Test (using Mocha)
```js
/* jshint expr:true */
import {
  describeComponent,
  it
} from 'ember-mocha';

describeComponent(
  'ui-radio',
  'UiRadioComponent',
  {
    //needs: ['component:radio-button']
  },
  function() {
    it('renders', function() {
      // creates the component instance
      var component = this.subject();
      expect(component._state).to.equal('preRender');

      // renders the component on the page
      this.render();
      expect(component._state).to.equal('inDOM');
    });
  }
);
```

Any help would be much appreciated.

**Comment by mansona** [comment]
I've mad a fix to master that should most likely fix all your issues. I haven't deployed it to npm yet because we haven't tested it on our apps, if it works ok for you please let me know

**Comment by slightlytyler** [comment]
We weren't able to get the component working when installed via github, not sure if it's an issue with component or ember-cli.

**Comment by mansona** [comment]
@slightlytyler I've updated the readme to explain what i believe is the "new way" to expose components in your app. I've tweeted @rwjblue about this to see if it's recommended but if you follow the new step in the readme it will work (i've tested it) 

Also I've published a version to npm (3.0.1) that i've tested and i'm confident is working. Please let me know if this is fixing your tests too

**Comment by slightlytyler** [comment]
@mansona works great! Thanks for the update

**Comment by mansona** [comment]
always a pleasure :wink:
