### ISSUE TITLE
Add action support

### ISSUE THREAD

**Issue by Globegitter** [Blooie/ember-radio-buttons#4]
It seems that `{{radio-button name="test" action="incrementCount"}}` doesn't call the action in the controller.
Is this helper supposed to have action support? Or is this a planned feature?

**Comment by mansona** [comment]
Hey @Globegitter , thanks for the suggestion. I'm trying to think what the benefit of having action support would be, maybe you could give a use case we could discuss? 

If you wanted to do something when something changed you could do something like this: 
```hbs
// app/templates/application.hbs
{{radio-button value='one' checked=selectedNumber}
```

```js
// app/controllers/application.js
...
    selectedNumberChanged: function(){
      console.log('the selected number is now %@'.fmt(this.get('selectedNumber')))
    }.observes('selectedNumber'),
...
```

**Comment by mansona** [comment]
closing this for now, just let me know if you want to discuss this any more and i'll reopen
