### ISSUE TITLE
How to add disable attribute to radio button

### ISSUE THREAD

**Issue by dmuneras** [Blooie/ember-radio-buttons#8]
Hi, 

It is a question not a issue, I just want to know how can I set the disabled property to the radio, I don't want to do something like:

document.getElementById("blablabla").disabled = true;

Best regards,
Daniel.

**Comment by ynnoj** [comment]
You can add `disabled=true` to the component helper.

```
{{radio-button value='green' checked=flavour disabled=true}}
```

See [#6](https://github.com/Blooie/ember-radio-buttons/pull/6).

**Comment by dmuneras** [comment]
Hi @ynnoj

Thanks for your quick answer, I tried but I didn't work, I think it is because I was using an older version. Now I install de last one, but I am getting an error following the instructions in the README. #7

I restart the server and reinstall the npm modules but it still not working.

I created the component using ember generate component and add the code to expose de helper, but I get 'ENOENT, no such file or directory'
